#---
#- name: Pull docker image from dockerhub
#  hosts: all
#  tasks:
#    - name: Pull docker image
#      docker_image:
#        name: sukrutdekhane/speminiproject
#        source: pull
---
- name: Pull docker image from dockerhub
  hosts: all
  tasks:
    - name: Pull docker image
      docker_image:
        name: sukrutdekhane/speminiproject
        source: pull
    - name: Create image
      shell: docker run -it --name mycontainer sukrutdekhane/speminiproject